# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0a03d907dc6d2d9e5abc6bb5ad14c8511830880d721f32b764d1fa6034418d59d7e1cf3b87ee43f631229961c736bc4c3b54b8b06f503c0b5acbe7fe3a65b25

test:
  secret_key_base: b8767eb80bd91b5b552f095bb3015b67bd8aed9a3e7a6e22c92537c9c82577169449a40d30d1ee42505916aed5581f2227e3c72a9c589b49f7686308f813bc58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
